changelog:
  categories:
    - title: '💥 BREAKING CHANGE'
      labels: ['BREAKING CHANGE']
    - title: '⚠️ DEPRECATED'
      labels: [DEPRECATED]
    - title: '🚀 Features'
      labels: [feat, perf]
    - title: '🐛 Bug Fixes'
      labels: [fix]
    - title: '⏪ Reverts'
      labels: [revert]
    - title: '🚩 Flags'
      labels: [flags]
    - title: '📝 Documentation'
      labels: [docs]
    - title: '🧹 Maintenance'
      labels: [refactor, style, test, build, ci, chore]
    - title: '🔧 Other Changes'
      labels: ['*']
